# Generated by Django 5.2.15 on 2026-07-05 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vanpresalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vanpresalary',
            options={'ordering': ['-year', '-total_pay']},
        ),
        migrations.RenameField(
            model_name='predictionrequest',
            old_name='prediction',
            new_name='prediction_result',
        ),
        migrations.RemoveField(
            model_name='vanpresalary',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vanpresalary',
            name='month',
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='agency',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='base_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='benefits',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='employee_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='other_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='overtime_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='total_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanpresalary',
            name='total_pay_benefits',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vanpresalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
