# Generated by Django 5.0.6 on 2026-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(default="Staff", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(default="Active", max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
